### ISSUE TITLE
LCD screen this GAP8 Gapuino board

### ISSUE THREAD

**Issue by diliplilaramani** [GreenWaves-Technologies/gap_applications#1]
Hi guys, can you tell me which LCD screen this GAP8 Gapuino board supports as shown in this video?

**Comment by Pafrak** [comment]
Dear dilipajm, 
this is the model: https://www.adafruit.com/product/1947

**Comment by diliplilaramani** [comment]
Thanks @Pafrak for quick reply. But in this [video](https://youtu.be/KN9mOmHrM7M?t=20) its telling 3.2 inches LCD Screen without capacitive touch.
